import { Hostage } from './app.interfaces';

export const hostages: Hostage[] = [
  {
    name: 'ליאת אצילי',
    age: '49',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/hwkpollk/ליאת-אצילי.jpg',
  },
  {
    name: 'אביב אצילי',
    age: '49',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/oivl5pdf/אביב-אצילי.jpg',
  },
  {
    name: 'איתן מור',
    age: '23',
    address: ' ירושלים',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/spnagum2/איתן-מור.jpg',
  },
  {
    name: 'ג׳ודי ויינשטיין',
    age: '70',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/pz5jny0l/ג-ודי-ויינשטיין.jpg',
  },
  {
    name: 'איתן לוי',
    age: '53',
    address: ' בת ים',
    tag: 'נחטף בדרכו לקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/qt5dzlu0/איתן-לוי.jpg',
  },
  {
    name: 'יוסף אלזיאדנה',
    age: '53',
    address: ' רהט',
    tag: 'נחטף מקיבוץ חולית',
    img: 'https://cfcdn.kan.org.il/media/zqzlterr/יוסף-אלזיאדנה.jpg',
  },
  {
    name: 'מישל ניסנבאום',
    age: '59',
    address: ' שדרות',
    tag: 'נחטף מאזור רעים',
    img: 'https://cfcdn.kan.org.il/media/dh1jkpip/מישל-ניסנבאום.jpg',
  },
  {
    name: 'מתן צנגאוקר',
    age: '23',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/01fbqmzn/מתן-צנגאוקר.jpg',
  },
  {
    name: 'עמית סוסנה',
    age: '40',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/3cdiimun/עמית-סוסנה.jpg',
  },
  {
    name: 'גלי טרשנסקי',
    age: '13',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/5gype5fz/גלי-טרשנסקי.jpg',
  },
  {
    name: 'עדה שגיא',
    age: '75',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/k1bnhz4a/עדה-שגיא.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599452/',
  },
  {
    name: 'יונתן סמרנו',
    age: '21',
    address: ' תל אביב',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/iigne2zd/יונתן-סמרנו.jpg',
  },
  {
    name: 'אופליה רויטמן',
    age: '77',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/vocggjkp/אופליה-רויטמן.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/573750/',
  },
  {
    name: 'הילה רותם',
    age: '13',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/unmfwmki/הילה-שושני-רותם.jpg',
  },
  {
    name: 'רעיה רותם',
    age: '54',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/ir3fj2ag/רעיה-רותם.jpg',
  },
  {
    name: 'ליאם אור',
    age: '18',
    address: ' בארי',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/0ybp3y2v/אור-ליאם.jpg',
  },
  {
    name: 'אליקים ליבמן',
    age: '24',
    address: ' קרית ארבע',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/2dvbhl34/אליקים-ליבמן.jpg',
  },
  {
    name: 'אנדריי קוזלוב',
    age: '27',
    address: ' ראשון לציון',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/5jxpte2f/אנדריי-קוזלוב.jpg',
  },
  {
    name: 'שני גורן',
    age: '29',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/jsjdkpvo/שני-גורן.jpg',
  },
  {
    name: 'גדי חגי',
    age: '73 ',
    address: 'ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/gcmbegle/גדי-חגי.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599442/',
  },
  {
    name: 'עלמה אור',
    age: '13',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/5dmbmgi4/עלמה-אור.jpg',
  },
  {
    name: 'נועם אור',
    age: '17',
    address: ' בארי',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/bzsooeyf/נועם-אור.jpg',
  },
  {
    name: 'דרור אור',
    age: '46',
    address: ' בארי',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/fcgpxrod/דרור-אור.jpg',
  },
  {
    name: 'נוגה וייס',
    age: '18',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/0xunook4/נוגה-וייס.jpg',
  },
  {
    name: 'שירי וייס',
    age: '53',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/vqqfogw2/שירי-וייס.jpg',
  },
  {
    name: 'שגיא דקל חן',
    age: '35',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/uz1arkmf/שגיא-דקל-חן.jpg',
  },
  {
    name: 'אמילי הנד',
    age: '8',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/qcse1vid/אמילי-הנד.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/598473/',
  },
  {
    name: 'עדן ירושלמי',
    age: '24',
    address: ' תל אביב',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/xefo1ak5/עדן-ירושלמי.jpg',
  },
  {
    name: "נורלין אגוג'ו",
    age: '60',
    address: ' הפיליפינים',
    tag: 'נחטפה מקיבוץ נירים',
    img: 'https://cfcdn.kan.org.il/media/owxcklr1/נורלין-אגוגו.jpg',
  },
  {
    name: "ביפין ג'ושי",
    age: '23',
    address: ' נפאל',
    tag: 'נחטף מקיבוץ עלומים',
    img: 'https://cfcdn.kan.org.il/media/u53alnk0/ביפין-גושי.jpg',
  },
  {
    name: 'איציק אלגרט',
    age: '69',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/xlqpur2m/איציק-אלגרט.jpg',
  },
  {
    name: 'שלומי זיו',
    age: '39',
    address: ' אלקוש',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/d5abpgv1/שלומי-זיו.jpg',
  },
  {
    name: 'נדב פופלוול',
    age: '51',
    address: ' נירים',
    tag: 'נחטף מקיבוץ נירים',
    img: 'https://cfcdn.kan.org.il/media/dvblkbuc/נדב-פופלוול.jpg',
  },
  {
    name: 'חנה פרי',
    age: '79',
    address: ' נירים',
    tag: 'נחטפה מקיבוץ נירים',
    img: 'https://cfcdn.kan.org.il/media/4kooz5ip/חנה-פרי.jpg',
  },
  {
    name: 'חיים פרי',
    age: '79',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/is5nyb2h/חיים-פרי.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573764/',
  },
  {
    name: 'עידן אלכסנדר',
    age: '19',
    address: ' ארה"ב',
    tag: 'נחטף מהבסיס שבו שירת',
    img: 'https://cfcdn.kan.org.il/media/fc1grglo/עידן-אלכסנדר.jpg',
  },
  {
    name: 'אופיר צרפתי',
    age: '27',
    address: ' קרית ביאליק',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/0tnhov4k/אופיר-צרפתי.jpg',
  },
  {
    name: 'עפרה קידר',
    age: '70',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/5rvieykk/עפרה-קידר.jpg',
  },
  {
    name: 'אוריון הרננדס ראדו',
    age: '30',
    address: ' מקסיקו',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/aauhtew2/אוריון-הרננדס.jpg',
  },
  {
    name: 'אריה זלמנוביץ',
    age: '85',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/vwhotqkm/אריה-זלמנוביץ.jpg',
  },
  {
    name: 'אור יעקב',
    age: '16',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/5jefyjro/אור-יעקב.jpg',
  },
  {
    name: 'יגיל יעקב',
    age: '13',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/jykb2tpx/יגיל-יעקב.jpg',
  },
  {
    name: 'גיא אילוז',
    age: '26',
    address: ' תל אביב',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/oxbhpruf/גיא-אילוז.jpg',
  },
  {
    name: 'מרגלית מוזס',
    age: '77',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/lg3lt4ah/מרגלית-מוזס.jpg',
  },
  {
    name: 'איתי סבירסקי',
    age: '38',
    address: ' תל אביב',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/0paovuhb/איתי-סבירסקי.jpg',
  },
  {
    name: 'אלמוג סרוסי',
    age: '25',
    address: ' רעננה',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/xugc5p2z/אלמוג-סרוסי.jpg',
  },
  {
    name: 'עאישה אלזיאדנה',
    age: '17',
    address: ' רהט',
    tag: 'נחטפה מקיבוץ חולית',
    img: 'https://cfcdn.kan.org.il/media/2xolx4gm/299x231.jpg',
  },
  {
    name: 'עדן זכריה',
    age: '28',
    address: ' קרית שמונה',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/wqybklzr/עדן-זכריה.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/575191/',
  },
  {
    name: 'עמירם קופר',
    age: '84',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/tzuhhtle/עמירם-קופר.jpg',
  },
  {
    name: 'נועם אביגדורי',
    age: '12',
    address: ' הוד השרון',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/pfjfhkmh/נועם-אביגדורי.jpg',
    link: 'https://kan.org.il/content/kan/kan-11/p-578726/589189/',
  },
  {
    name: 'יאיר הורן',
    age: '45',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/ro5k3r50/יאיר-הורן.jpg',
  },
  {
    name: 'איתן הורן',
    age: '37',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/3iphiwvj/איתן-הורן.jpg',
  },
  {
    name: 'ליאור רודאיף',
    age: '61',
    address: ' ניר יצחק',
    tag: 'נחטף מקיבוץ ניר יצחק',
    img: 'https://cfcdn.kan.org.il/media/vctlnodp/398063883_10161431415177088_3568294037318690713_n.jpg',
  },
  {
    name: 'שרון אביגדורי',
    age: '52',
    address: ' הוד השרון',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/pjqpsmul/שרון-אביגדורי.jpg',
    link: 'https://kan.org.il/content/kan/kan-11/p-578726/589189/',
  },
  {
    name: 'זיו ברמן',
    age: '26',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/z1jna5gf/זיו-ברמן.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599405/',
  },
  {
    name: 'גלי ברמן',
    age: '26',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/l2jnxztx/גלי-ברמן.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599405/',
  },
  {
    name: 'אירנה טטי',
    age: '73',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/bceftxuw/אירנה-טטי.jpg',
  },
  {
    name: 'ספיר כהן',
    age: '29',
    address: ' קרית אתא',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/mlfb5wvx/ספיר-כהן.jpg',
  },
  {
    name: 'סשה אלכסנדר טרופנוב',
    age: '28',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/sxdpahk0/סשה-טרופנוב.jpg',
  },
  {
    name: 'עמית שני',
    age: '16',
    address: ' בארי',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/gcjpv1dv/עמית-שני.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599527/',
  },
  {
    name: 'יוסף חיים אוחנה',
    age: '23',
    address: ' קרית מלאכי',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/3etpew2g/יוסף-חיים-אוחנה.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599353/',
  },
  {
    name: 'יותם חיים',
    age: '28',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/4sop24pr/יותם-חיים.jpg',
  },
  {
    name: 'טל חיימי',
    age: '42',
    address: ' ניר יצחק',
    tag: 'נחטף מקיבוץ ניר יצחק',
    img: 'https://cfcdn.kan.org.il/media/dihhcxth/טל-חיימי.jpg',
  },
  {
    name: 'ירדן ביבס',
    age: '34',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/thincxoa/ירדן-ביבס.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599517/',
  },
  {
    name: 'חנה קציר',
    age: '77',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/2xnhrkwb/חנה-קציר.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599525/',
  },
  {
    name: 'שגב כלפון',
    age: '26',
    address: ' דימונה',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/lvujl0no/שגב-כלפון.jpg',
  },
  {
    name: 'תמיר אדר',
    age: '38',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/gh0pnm43/תמיר-אדר.jpg',
  },
  {
    name: 'תמיר נמרודי',
    age: '18',
    address: ' נירית',
    tag: 'נחטף מהבסיס שבו שירת',
    img: 'https://cfcdn.kan.org.il/media/l5pjgixc/תמיר-נמרודי.png',
    link: 'https://www.kan.org.il/content/kan/kan-11/p-12043/s7/590317/',
  },
  {
    name: 'נילי מרגלית',
    age: '41',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/q3cgmehm/נילי-מרגלית.jpg',
  },
  {
    name: 'יגב בוכשטב',
    age: '34',
    address: ' נירים',
    tag: 'נחטף מקיבוץ נירים',
    img: 'https://cfcdn.kan.org.il/media/1xwj2lci/יגב-בוכשטב.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599356/',
  },
  {
    name: 'רימון קירשט',
    age: '36',
    address: ' נירים',
    tag: 'נחטפה מקיבוץ נירים',
    img: 'https://cfcdn.kan.org.il/media/g5jjup1p/רימון-קירשט.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/590370/',
  },
  {
    name: 'ילנה טרופנוב',
    age: '50',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/n51jz3un/ילנה-טרופנוב.jpg',
    link: 'https://www.kan.org.il/content/kan-news/defense/588988/',
  },
  {
    name: 'רביד כץ',
    age: '51',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/rjgajtbw/רביד-כץ.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/580167/',
  },
  {
    name: 'דורון שטיינברכר',
    age: '30',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/us2oiep1/דורון-שטיינברכר.jpg',
  },
  {
    name: 'שלמה מנסור',
    age: '85',
    address: ' כיסופים',
    tag: 'נחטף מקיבוץ כיסופים',
    img: 'https://cfcdn.kan.org.il/media/550buqht/שלמה-מנסור.jpg',
  },
  {
    name: 'מיה גורן',
    age: '56 ',
    address: 'ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/u5bdgebv/מיה.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599485/',
  },
  {
    name: 'חמזה אלזיאדנה',
    age: '22',
    address: ' רהט',
    tag: 'נחטף מקיבוץ חולית',
    img: 'https://cfcdn.kan.org.il/media/uolppudl/חמזה-זיידנה.jpg',
  },
  {
    name: 'פרחאן אלקאדי',
    age: '53',
    address: ' דרומית לרהט',
    tag: 'נחטף מקיבוץ מגן',
    img: 'https://cfcdn.kan.org.il/media/btxjdueu/פרחאן-אלקאדי.jpg',
  },
  {
    name: 'בלאל אלזיאדנה',
    age: '19',
    address: ' רהט',
    tag: 'נחטף מקיבוץ חולית',
    img: 'https://cfcdn.kan.org.il/media/t5rbdhd4/בלאל-זיידנה.jpg',
  },
  {
    name: 'סאמר פואד אל-טלאלקה',
    age: '24',
    address: ' חורה',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/2ylncrow/סאמר-פואד-אל-טלאלקה.jpg',
  },
  {
    name: 'קלמנס מטנגה',
    age: '22',
    address: ' אזרח טנזניה',
    tag: 'נחטף מקיבוץ נחל עוז',
    img: 'https://cfcdn.kan.org.il/media/1rseqjdk/קלמנס-מטנגה.jpg',
  },
  {
    name: "ג'ושוע לואיטו מולל",
    age: '21',
    address: ' אזרח טנזניה',
    tag: 'נחטף מקיבוץ נחל עוז',
    img: 'https://cfcdn.kan.org.il/media/2ldfddes/גושוע-לואיטו.jpg',
  },
  {
    name: 'ירדן רומן',
    age: '36',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/g1gaujvo/ירדן-רומן.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573761/',
  },
  {
    name: 'דולב יהוד',
    age: '35',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/zrvfaqdk/דולב-יהוד.jpg',
  },
  {
    name: 'ארבל יהוד',
    age: '28',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/bgjgwboe/ארבל-יהוד.jpg',
  },
  {
    name: 'טל גולדשטיין',
    age: '9',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/xrzchkek/טל-גולדשטיין.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/568697/',
  },
  {
    name: 'גל גולדשטיין',
    age: '11',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/dbbfhz4l/גל-גולדשטיין.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/568697/',
  },
  {
    name: 'אגם גולדשטיין',
    age: '17',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/5mllhmx2/אגם-גולדשטיין.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/568697/',
  },
  {
    name: 'חן אלמוג גולדשטיין',
    age: '48',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/301fo51f/חן-אלמוג-גולדשטיין.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/568697/',
  },
  {
    name: 'אלון לולו שמריז',
    age: '26',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/4iupxan1/אלון-לולו-שמריז.jpg',
  },
  {
    name: 'רומי גונן',
    age: '23',
    address: ' כפר ורדים',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/44jkbzmb/רומי-לשם-גונן.jpg',
    link: 'https://www.kan.org.il/content/kan-news/opinions/589039/',
  },
  {
    name: 'אלכס דנציג',
    age: '75',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/hnqicez5/אלכס-דנציג.jpg',
    link: 'https://www.kan.org.il/content/kan/podcasts/p-569737/583124/',
  },
  {
    name: 'יובל אנגל',
    age: '11',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/uqhfabl4/יובל-אנגל.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573742/',
  },
  {
    name: 'מיקה אנגל',
    age: '18',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/pbkpcxs5/מיקה-אנגל.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573742/',
  },
  {
    name: 'רונן אנגל',
    age: '55',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/io2ote30/רונן-אנגל.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573742/',
  },
  {
    name: 'קרינה אנגל-ברט',
    age: '51',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/bwzjzahj/קרינה-אנגל.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573742/',
  },
  {
    name: 'יהל שוהם',
    age: '3',
    address: ' מעלה צביה',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/1atcuddn/yahel1.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/581493/',
  },
  {
    name: 'נווה שוהם',
    age: '8',
    address: ' מעלה צביה',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/k0ep5kxj/nave.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/581493/',
  },
  {
    name: 'טל שוהם',
    age: '38',
    address: ' מעלה צביה',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/n3wdekrn/tal.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/581493/',
  },
  {
    name: 'עדי שוהם',
    age: '38',
    address: ' מעלה צביה',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/kfehmkny/עדי-שוהם-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/581493/',
  },
  {
    name: 'עמית בוסקילה',
    age: '28',
    address: ' אשדוד',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/jzpfozkl/amit.jpg',
  },
  {
    name: 'לואיס נורברטו הר',
    age: '70',
    address: ' אורים',
    tag: 'נחטף מקיבוץ ניר יצחק',
    img: 'https://cfcdn.kan.org.il/media/ae2b5svh/לואיס-נורברטו-הר.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573749/',
  },
  {
    name: 'ניק בייזר',
    age: '19',
    address: ' באר שבע',
    tag: 'נחטף מהסיס שבו שירת',
    img: 'https://cfcdn.kan.org.il/media/23jbzvlj/nik.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-11/p-12043/s7/590317/',
  },
  {
    name: 'אלקנה בוחבוט',
    age: '34',
    address: ' מבשרת ציון',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/hozf3yhf/אלקנה-בוחבוט-פייסבוק.jpg',
  },
  {
    name: 'אלי שרעבי',
    age: '51',
    address: ' בארי',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/ktpjpk0d/אלי-שרעבי-פייסבוק.jpg',
  },
  {
    name: 'הירש גולדברג פולין',
    age: '23',
    address: ' ירושלים',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/4kkdceul/הירש-גולדברג-פולין-פייסבוק.jpg',
  },
  {
    name: 'דניאלה גלבוע',
    age: '19',
    address: ' פתח תקווה',
    tag: 'נחטפה מהבסיס שבו שירתה',
    img: 'https://cfcdn.kan.org.il/media/tpqhy4kk/דניאלה-גלבוע.jpg',
  },
  {
    name: 'רוני קריבוי',
    age: '25',
    address: ' כרמיאל',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/ql3hysd3/רוני-קריבוי-פייסבוק.png',
  },
  {
    name: 'עדינה משה',
    age: '72',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/5s0fhvml/eyal-nouri.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573763/',
  },
  {
    name: 'גיא גלבוע דלאל',
    age: '22',
    address: ' כפר סבא',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/klbbedaj/גיא-גלבוע-דלאל.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599462/',
  },
  {
    name: 'צחי עידן',
    age: '49',
    address: ' נחל עוז',
    tag: 'נחטף מקיבוץ נחל עוז',
    img: 'https://cfcdn.kan.org.il/media/wnjjb4hr/צחי-עידן-פייסבוק.jpg',
  },
  {
    name: 'אילנה גריצבסקי',
    age: '30',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/mdofvb3g/אילנה-גריצבסקי-פייסבוק.png',
  },
  {
    name: 'עודד ליפשיץ',
    age: '83',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/23fdh13r/עודד-ליפשיץ-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan-news/local/580269/',
  },
  {
    name: 'רז בן עמי',
    age: '57',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/435hgk32/רז-בן-עמי.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599516/',
  },
  {
    name: 'מורן ינאי',
    age: '40',
    address: ' באר שבע',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/mq3ntych/מורן-ינאי.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599427/',
  },
  {
    name: 'כרמל גת',
    age: '39',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/saufx1dc/כרמל-גת-פייסבוק.jpg',
  },
  {
    name: 'שושן הרן',
    age: '67',
    address: ' בארי',
    tag: 'נחטפה מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/swpiw402/שושן-הרן-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan-news/local/574933/',
  },
  {
    name: 'גדי משה מוזס',
    age: '79',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/5i3piivv/gadi.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/580167/',
  },
  {
    name: 'סהר קלדרון',
    age: '16',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/brfd5m1l/סהר-קלדרון.jpg',
    link: 'https://www.kan.org.il/content/kan-news/local/585082/',
  },
  {
    name: 'ארז קלדרון',
    age: '12',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/ex2bmz0l/ארז-קלדרון-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan-news/local/583488/',
  },
  {
    name: 'עופר קלדרון',
    age: '50',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/o4fhoryx/עופר-קלדרון-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan-news/local/585082/',
  },
  {
    name: 'נעמה לוי',
    age: '19',
    address: ' רעננה',
    tag: 'נחטפה מהבסיס שבו שירתה',
    img: 'https://cfcdn.kan.org.il/media/d0vfsncw/נעמה-לוי-פייסבוק.jpg',
  },
  {
    name: 'תמר מצגר',
    age: '78',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/jhjai4vn/תמר-מצגר.png',
    link: 'https://www.kan.org.il/content/kan/podcasts/p-579653/191023/587974/',
  },
  {
    name: 'יורם מצגר',
    age: '80',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/n3rg2fgi/יורם-מצגר.png',
    link: 'https://www.kan.org.il/content/kan/podcasts/p-579653/191023/587974/',
  },
  {
    name: "אלמוג מאיר ג'אן",
    age: '21',
    address: ' אור יהודה',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/50bnkspr/אלמוג-מאיר-גאן-פייסבוק.png',
  },
  {
    name: 'אלון אהל',
    age: '22',
    address: ' לבון',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/pzmjy5jv/אלון-אהל-פייסבוק.png',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599473/',
  },
  {
    name: 'עומר שם טוב',
    age: '21',
    address: ' הרצליה',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/sa1h5hgt/עומר-שם-טוב.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573754/',
  },
  {
    name: 'עמרי מירן',
    age: '46',
    address: ' נחל עוז',
    tag: 'נחטף מקיבוץ נחל עוז',
    img: 'https://cfcdn.kan.org.il/media/d0wbzmfm/עותק-של-lishay_lavi.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573758/',
  },
  {
    name: 'יולי קוניו',
    age: '3',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/h4oipf4t/אמה-קוניו-יולי-קוניו-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573760/',
  },
  {
    name: 'אמה קוניו',
    age: '3',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/h4oipf4t/אמה-קוניו-יולי-קוניו-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573760/',
  },
  {
    name: 'דוד קוניו',
    age: '33',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/3wbdqmdm/דוד-קוניו.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573760/',
  },
  {
    name: 'שרון אלוני קוניו',
    age: '34',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/a0xp5mvp/שרון-אלוני-קוניו.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573760/',
  },
  {
    name: 'קרינה ארייב',
    age: '19',
    address: ' ירושלים',
    tag: 'נחטפה מהבסיס שבו שירתה',
    img: 'https://cfcdn.kan.org.il/media/u3flmqmg/קרינה-ארייב.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/575129/',
  },
  {
    name: 'איתי רגב',
    age: '18',
    address: ' הרצליה',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/3s0l5sdc/איתי-רגב.jpg',
  },
  {
    name: 'מיה רגב',
    age: '21',
    address: ' הרצליה',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/5hcpvoxb/מיה-רגב.jpg',
  },
  {
    name: 'אביתר דוד',
    age: '23',
    address: ' כפר סבא',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/5c3fotvc/אביתר-דוד-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573745/',
  },
  {
    name: 'אלה אליקים',
    age: '8',
    address: ' נחל עוז',
    tag: 'נחטפה מקיבוץ נחל עוז',
    img: 'https://cfcdn.kan.org.il/media/w03j4aa4/אלה-אליקים-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573748/',
  },
  {
    name: 'דפנה אליקים',
    age: '15',
    address: ' נחל עוז',
    tag: 'אלה אליקים',
    img: 'https://cfcdn.kan.org.il/media/fstng4tp/דפנה-אליקים-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573748/',
  },
  {
    name: 'דיצה הימן',
    age: '84',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/o3wnpk1b/דיצה-הימן.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/575122/',
  },
  {
    name: 'אמיליה אלוני',
    age: '6',
    address: ' יבנה',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/4hlc1fuq/אמיליה-אלוני.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573760/',
  },
  {
    name: 'דניאל אלוני',
    age: '45',
    address: ' יבנה',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/0dkhrv4r/דניאל-אלוני-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573760/',
  },
  {
    name: 'אופיר אנגל',
    age: '17',
    address: ' רמת רחל',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/55ldgatc/אופיר-אנגל-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599531/',
  },
  {
    name: 'רון שרמן',
    age: '19',
    address: ' להבים',
    tag: 'נחטף מהבסיס שבו שירת',
    img: 'https://cfcdn.kan.org.il/media/wy3jdkqy/רון-שרמן-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599433/',
  },
  {
    name: 'אוהד מונדר זכרי',
    age: '9',
    address: ' כפר סבא',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/sv0nv5aa/אוהד-מונדר.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/580186/',
  },
  {
    name: 'קרן מונדר',
    age: '54',
    address: ' כפר סבא',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/qksjzge3/קרן-מונדר-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/580186/',
  },
  {
    name: 'רותי מונדר',
    age: '78',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/el0bcjtb/רותי-מונדר-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/580186/',
  },
  {
    name: 'אברהם מונדר',
    age: '78',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/epwbr2yu/אברהם-מונדר-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/580186/',
  },
  {
    name: 'איתן יהלומי',
    age: '12',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/hbxmopoz/איתן-יהלומי-פייסבוק.jpg',
  },
  {
    name: 'אוהד יהלומי',
    age: '49',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/hdgpf5b1/אוהד-יהלומי-פייסבוק.png',
  },
  {
    name: 'אוהד בן עמי',
    age: '55',
    address: ' בארי',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/o03lbwnv/אוהד-בן-עמי-פייסבוק.png',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599516/',
  },
  {
    name: 'אגם ברגר',
    age: '20',
    address: ' חולון',
    tag: 'נחטפה מהבסיס שבו שירתה',
    img: 'https://cfcdn.kan.org.il/media/stcnj1h5/אגם-ברבר-פייסבוק.jpg',
  },
  {
    name: "קית' שמואל סגל",
    age: '64',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/ljgpdu3f/קית-שמואל-סגל-פייסבוק.png',
  },
  {
    name: 'אדריאן אביבה סגל',
    age: '62',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/fvnaggn2/אביבה-סגל-פייסבוק.png',
  },
  {
    name: 'עפרי ברודץ',
    age: '10',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/zhmg3x4f/עפרי-ברודץ-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan-news/defense/567783/',
  },
  {
    name: 'אוריה ברודץ',
    age: '4',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/z32btey2/אוריה-ברודץ-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan-news/defense/567783/',
  },
  {
    name: 'יובל ברודץ',
    age: '8',
    address: ' כפר עזה',
    tag: 'נחטף מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/qfwdszd5/יובל-ברודץ-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan-news/defense/567783/',
  },
  {
    name: 'הגר ברודץ',
    age: '39',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/enzfkvur/הגר-ברודץ.jpg',
    link: 'https://www.kan.org.il/content/kan-news/defense/567783/',
  },
  {
    name: 'יאיר יעקב',
    age: '59',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/lrzexerv/yair.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/568687/',
  },
  {
    name: 'מירב טל',
    age: '53',
    address: ' ראשון לציון',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/44ifrr3o/מירב-טל-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/589205/',
  },
  {
    name: 'אור לוי',
    age: '33',
    address: ' גבעתיים',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/1elhpajx/אור-לוי-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599495/',
  },
  {
    name: 'אליה כהן',
    age: '26',
    address: ' צור הדסה',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/cxcli1sl/sigicohen.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573755/',
  },
  {
    name: 'אבינתן אור',
    age: '30',
    address: ' תל אביב',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/k3lieyfd/אבינתן-אור.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599518/',
  },
  {
    name: 'נועה ארגמני',
    age: '26',
    address: ' באר שבע',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/rs0bky4a/נועה-ארגמני.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573751/',
  },
  {
    name: 'יוסי שרעבי',
    age: '53',
    address: ' בארי',
    tag: 'נחטף מקיבוץ בארי',
    img: 'https://cfcdn.kan.org.il/media/jjupebsa/יוסי-שרעבי-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599526/',
  },
  {
    name: 'כפיר ביבס',
    age: '9 חודשים',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/exzjde0a/כפיר-ביבס-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/572854/',
  },
  {
    name: 'אריאל ביבס',
    age: '4',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/minpipqz/אריאל-ביבס-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/572854/',
  },
  {
    name: 'שירי ביבס',
    age: '32',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/isunzplk/שירי-ביבס-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/kan-actual/p-11894/news-item/572854/',
  },
  {
    name: 'אלמה אברהם',
    age: '84',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/ytchfvi1/אלמה-אברהם-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/573756/',
  },
  {
    name: 'לירי אלבג',
    age: '18',
    address: ' ירחיב',
    tag: 'נחטפה מהבסיס שבו שירתה',
    img: 'https://cfcdn.kan.org.il/media/teifnkfv/לירי-אלבג-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599406/',
  },
  {
    name: 'בר קופרשטיין',
    age: '22',
    address: ' חולון',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/u0rkyadc/בר-קופרשטיין-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599528/',
  },
  {
    name: 'מייה שם',
    age: '21',
    address: ' שוהם',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/znnlzfgn/מייה-שם-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599519/',
  },
  {
    name: 'אביב כץ אשר',
    age: '2',
    address: ' גנות הדר',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/50tje5h2/אביב-כץ-אשר-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/580167/',
  },
  {
    name: 'רז כץ אשר',
    age: '4',
    address: ' גנות הדר',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/nsmgyabk/רז-כץ-אשר-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/580167/',
  },
  {
    name: 'דורון כץ אשר',
    age: '34',
    address: ' גנות הדר',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/gyfdafx4/דורון-כץ-אשר-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/580167/',
  },
  {
    name: 'מייה ליימברג',
    age: '17',
    address: ' ירושלים',
    tag: 'נחטפה מקיבוץ ניר יצחק',
    img: 'https://cfcdn.kan.org.il/media/z4wlmsmj/מייה-ליימברג-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573749/',
  },
  {
    name: 'גבריאלה ליימברג',
    age: '59',
    address: ' ירושלים',
    tag: 'נחטפה מקיבוץ ניר יצחק',
    img: 'https://cfcdn.kan.org.il/media/pegm0k2q/גבריאלה-ליימברג-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573749/',
  },
  {
    name: 'פרננדו מרמן',
    age: '60',
    address: ' כפר סבא',
    tag: 'נחטף מקיבוץ ניר יצחק',
    img: 'https://cfcdn.kan.org.il/media/eddfula3/פרננדו-מרמן.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573749/',
  },
  {
    name: 'קלרה מרמן',
    age: '63',
    address: ' ניר יצחק',
    tag: 'נחטפה מקיבוץ ניר יצחק',
    img: 'https://cfcdn.kan.org.il/media/qdafpcx1/קלרה-מרמן-פייסבוק.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573749/',
  },
  {
    name: 'עומר ונקרט',
    age: '22',
    address: ' גדרה',
    tag: 'נחטף מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/seeovmba/עומר-ונקרט-פייסבוק.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599355/',
  },
  {
    name: 'אלעד קציר',
    age: '47',
    address: ' ניר עוז',
    tag: 'נחטף מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/cr1hoaob/אלעד-קציר.jpg',
    link: 'https://kan.org.il/content/kan/special-sections/p-571459/599525/',
  },
  {
    name: 'אביגיל עידן',
    age: '3',
    address: ' כפר עזה',
    tag: 'נחטפה מקיבוץ כפר עזה',
    img: 'https://cfcdn.kan.org.il/media/qsudzpkz/אביגיל-עידן-פייסבוק.jpg',
    link: 'https://twitter.com/kann_news/status/1715640878230897066',
  },
  {
    name: 'יפה אדר',
    age: '85',
    address: ' ניר עוז',
    tag: 'נחטפה מקיבוץ ניר עוז',
    img: 'https://cfcdn.kan.org.il/media/ctkhujhs/יפה-אדר.png',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573752/',
  },
  {
    name: 'ענבר הימן',
    age: '27',
    address: ' חיפה',
    tag: 'נחטפה מהמסיבה ברעים',
    img: 'https://cfcdn.kan.org.il/media/nnkcyc1t/ענבר-הימן-פייסבוק.jpg',
    link: 'https://www.kan.org.il/content/kan/special-sections/p-571459/573746/',
  },
];
